In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('D:/DSP/customer_churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [11]:
df.drop('customerID',axis=1,inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [13]:
df[pd.to_numeric(df['TotalCharges'],errors='coerce').isnull()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [14]:
df1=df[df['TotalCharges']!=' ']

df1.shape

In [15]:
df1.shape

(7032, 20)

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   object
 19  Churn             7032 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [18]:
df1['TotalCharges']=pd.to_numeric(df1['TotalCharges'])

C:\Users\PallaviVanga\AppData\Local\Temp\ipykernel_42856\2549848952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['TotalCharges']=pd.to_numeric(df1['TotalCharges'])

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [20]:
def print_unique_values(df):
    for column in df:
        if df[column].dtypes=='object':
            print(f'{column}:{df[column].unique()}')

In [21]:
print_unique_values(df1)

gender:['Female' 'Male']
Partner:['Yes' 'No']
Dependents:['No' 'Yes']
PhoneService:['No' 'Yes']
MultipleLines:['No phone service' 'No' 'Yes']
InternetService:['DSL' 'Fiber optic' 'No']
OnlineSecurity:['No' 'Yes' 'No internet service']
OnlineBackup:['Yes' 'No' 'No internet service']
DeviceProtection:['No' 'Yes' 'No internet service']
TechSupport:['No' 'Yes' 'No internet service']
StreamingTV:['No' 'Yes' 'No internet service']
StreamingMovies:['No' 'Yes' 'No internet service']
Contract:['Month-to-month' 'One year' 'Two year']
PaperlessBilling:['Yes' 'No']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn:['No' 'Yes']

In [22]:
df1.replace('No internet service','No',inplace=True)

C:\Users\PallaviVanga\AppData\Local\Temp\ipykernel_42856\3939576099.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace('No internet service','No',inplace=True)

In [23]:
df1.replace('No phone service','No',inplace=True)

C:\Users\PallaviVanga\AppData\Local\Temp\ipykernel_42856\628100714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace('No phone service','No',inplace=True)

In [24]:
print_unique_values(df1)

gender:['Female' 'Male']
Partner:['Yes' 'No']
Dependents:['No' 'Yes']
PhoneService:['No' 'Yes']
MultipleLines:['No' 'Yes']
InternetService:['DSL' 'Fiber optic' 'No']
OnlineSecurity:['No' 'Yes']
OnlineBackup:['Yes' 'No']
DeviceProtection:['No' 'Yes']
TechSupport:['No' 'Yes']
StreamingTV:['No' 'Yes']
StreamingMovies:['No' 'Yes']
Contract:['Month-to-month' 'One year' 'Two year']
PaperlessBilling:['Yes' 'No']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn:['No' 'Yes']

In [25]:
df1.replace({'Yes':1,'No':0},inplace=True)

C:\Users\PallaviVanga\AppData\Local\Temp\ipykernel_42856\1911272350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace({'Yes':1,'No':0},inplace=True)

In [26]:
print_unique_values(df1)

gender:['Female' 'Male']
InternetService:['DSL' 'Fiber optic' 0]
Contract:['Month-to-month' 'One year' 'Two year']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [27]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,1,0,1,0,0,DSL,0,1,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,Male,0,0,0,34,1,0,DSL,1,0,1,0,0,0,One year,0,Mailed check,56.95,1889.50,0
2,Male,0,0,0,2,1,0,DSL,1,1,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,Male,0,0,0,45,0,0,DSL,1,0,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,0,0,2,1,0,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1

In [29]:
df1.replace({'Female':1,'Male':0},inplace=True)

C:\Users\PallaviVanga\AppData\Local\Temp\ipykernel_42856\1354560788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.replace({'Female':1,'Male':0},inplace=True)

In [30]:
df1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,1,0,1,0,0,DSL,0,1,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,0,0,0,0,34,1,0,DSL,1,0,1,0,0,0,One year,0,Mailed check,56.95,1889.50,0
2,0,0,0,0,2,1,0,DSL,1,1,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,0,0,0,0,45,0,0,DSL,1,0,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,1,0,0,0,2,1,0,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1

In [31]:
df2=pd.get_dummies(data=df1,columns=['InternetService','Contract','PaymentMethod'])

In [32]:
df2.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InternetService_0', 'InternetService_DSL',
       'InternetService_Fiber optic', 'Contract_Month-to-month',
       'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [33]:
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_0,InternetService_DSL,InternetService_Fiber optic,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,1,0,0,0,1,0,...,0,1,0,1,0,0,0,0,1,0
1,0,0,0,0,34,1,0,1,0,1,...,0,1,0,0,1,0,0,0,0,1
2,0,0,0,0,2,1,0,1,1,0,...,0,1,0,1,0,0,0,0,0,1
3,0,0,0,0,45,0,0,1,0,1,...,0,1,0,0,1,0,1,0,0,0
4,1,0,0,0,2,1,0,0,0,0,...,0,0,1,1,0,0,0,0,1,0

In [34]:
cols_to_scale=['tenure','MonthlyCharges','TotalCharges']

In [35]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df2[cols_to_scale]=scaler.fit_transform(df2[cols_to_scale])

In [36]:
df2[cols_to_scale]

        tenure  MonthlyCharges  TotalCharges
0     0.000000        0.115423      0.001275
1     0.464789        0.385075      0.215867
2     0.014085        0.354229      0.010310
3     0.619718        0.239303      0.210241
4     0.014085        0.521891      0.015330
...        ...             ...           ...
7038  0.323944        0.662189      0.227521
7039  1.000000        0.845274      0.847461
7040  0.140845        0.112935      0.037809
7041  0.042254        0.558706      0.033210
7042  0.915493        0.869652      0.787641

[7032 rows x 3 columns]

In [37]:
df2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_0,InternetService_DSL,InternetService_Fiber optic,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,0,1,0,0.000000,0,0,0,1,0,...,0,1,0,1,0,0,0,0,1,0
1,0,0,0,0,0.464789,1,0,1,0,1,...,0,1,0,0,1,0,0,0,0,1
2,0,0,0,0,0.014085,1,0,1,1,0,...,0,1,0,1,0,0,0,0,0,1
3,0,0,0,0,0.619718,0,0,1,0,1,...,0,1,0,0,1,0,1,0,0,0
4,1,0,0,0,0.014085,1,0,0,0,0,...,0,0,1,1,0,0,0,0,1,0

In [38]:
df2.sample(3)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_0,InternetService_DSL,InternetService_Fiber optic,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
2401,0,1,0,1,0.140845,1,0,0,1,0,...,0,1,0,1,0,0,0,0,1,0
4499,1,0,0,1,0.154930,1,1,1,0,0,...,0,0,1,1,0,0,0,0,1,0
1462,0,0,1,0,0.492958,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,1

In [39]:
for col in df2:
    print(f'{col}:{df2[col].unique()}')

gender:[1 0]
SeniorCitizen:[0 1]
Partner:[1 0]
Dependents:[0 1]
tenure:[0.         0.46478873 0.01408451 0.61971831 0.09859155 0.29577465
 0.12676056 0.38028169 0.85915493 0.16901408 0.21126761 0.8028169
 0.67605634 0.33802817 0.95774648 0.71830986 0.98591549 0.28169014
 0.15492958 0.4084507  0.64788732 1.         0.22535211 0.36619718
 0.05633803 0.63380282 0.14084507 0.97183099 0.87323944 0.5915493
 0.1971831  0.83098592 0.23943662 0.91549296 0.11267606 0.02816901
 0.42253521 0.69014085 0.88732394 0.77464789 0.08450704 0.57746479
 0.47887324 0.66197183 0.3943662  0.90140845 0.52112676 0.94366197
 0.43661972 0.76056338 0.50704225 0.49295775 0.56338028 0.07042254
 0.04225352 0.45070423 0.92957746 0.30985915 0.78873239 0.84507042
 0.18309859 0.26760563 0.73239437 0.54929577 0.81690141 0.32394366
 0.6056338  0.25352113 0.74647887 0.70422535 0.35211268 0.53521127]
PhoneService:[0 1]
MultipleLines:[0 1]
OnlineSecurity:[0 1]
OnlineBackup:[1 0]
DeviceProtection:[0 1]
TechSupport:[0 1]
StreamingTV:[0 1]
StreamingMovies:[0 1]
PaperlessBilling:[1 0]
MonthlyCharges:[0.11542289 0.38507463 0.35422886 ... 0.44626866 0.25820896 0.60149254]
TotalCharges:[0.0012751  0.21586661 0.01031041 ... 0.03780868 0.03321025 0.78764136]
Churn:[0 1]
InternetService_0:[0 1]
InternetService_DSL:[1 0]
InternetService_Fiber optic:[0 1]
Contract_Month-to-month:[1 0]
Contract_One year:[0 1]
Contract_Two year:[0 1]
PaymentMethod_Bank transfer (automatic):[0 1]
PaymentMethod_Credit card (automatic):[0 1]
PaymentMethod_Electronic check:[1 0]
PaymentMethod_Mailed check:[0 1]

In [40]:
x=df2.drop('Churn',axis=1)
y=df2['Churn']

In [41]:
x.shape

(7032, 26)

In [42]:
y.shape

(7032,)

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
#By using Under Sampling technique:

In [53]:
#class count
count_class_0,count_class_1=df2.Churn.value_counts()

In [54]:
count_class_0

5163

In [55]:
count_class_1

1869

In [50]:
df_class_0=df2[df2['Churn']==0]
df_class_1=df2[df2['Churn']==1]

In [51]:
df_class_0.shape

(5163, 27)

In [52]:
df_class_1.shape

(1869, 27)

In [58]:
df_class_0.sample(count_class_1).shape

(1869, 27)

In [59]:
df_class_0.sample(count_class_0).shape

(5163, 27)

In [61]:
df_class_1.sample(count_class_1).shape

(1869, 27)

In [67]:
df_class_0_under=df_class_0.sample(count_class_1)
df_test_under=pd.concat([df_class_0_under,df_class_1],axis=0)
print('Random under-sampling:')
print(df_test_under.Churn.value_counts())

Random under-sampling:
0    1869
1    1869
Name: Churn, dtype: int64

In [64]:
df_class_0_under.shape

(1869, 27)

In [65]:
df_class_1.shape

(1869, 27)

In [66]:
df_test_under.shape

(3738, 27)

In [68]:
x=df_test_under.drop('Churn',axis=1)
y=df_test_under['Churn']

In [69]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=15,stratify=y)

In [70]:
y_train.shape

(2990,)

In [71]:
y_train.value_counts()

0    1495
1    1495
Name: Churn, dtype: int64

In [72]:
from sklearn.metrics import confusion_matrix,classification_report

In [75]:
def ANN(x_train,y_train,x_test,y_test,loss):
    model=keras.Sequential([keras.layers.Dense(26,input_dim=26,activation='relu'),
                           keras.layers.Dense(15,activation='relu'),
                           keras.layers.Dense(1,activation='sigmoid')])
    model.compile(optimizer='adam',loss=loss,metrics=['accuracy'])
    model.fit(x_train,y_train,epochs=100)
    print(model.evaluate(x_test,y_test))
    y_pred=model.predict(x_test)
    y_pred=np.round(y_pred)
    print("classification report: \n", classification_report(y_test,y_pred))
    return y_pred

In [76]:
y_pred=ANN(x_train,y_train,x_test,y_test,'binary_crossentropy')

Epoch 1/100
94/94 [==============================] - 0s 654us/step - loss: 0.6017 - accuracy: 0.7000
Epoch 2/100
94/94 [==============================] - 0s 661us/step - loss: 0.5042 - accuracy: 0.7565
Epoch 3/100
94/94 [==============================] - 0s 665us/step - loss: 0.4908 - accuracy: 0.7645
Epoch 4/100
94/94 [==============================] - 0s 665us/step - loss: 0.4870 - accuracy: 0.7619
Epoch 5/100
94/94 [==============================] - 0s 654us/step - loss: 0.4814 - accuracy: 0.7686
Epoch 6/100
94/94 [==============================] - 0s 665us/step - loss: 0.4786 - accuracy: 0.7669
Epoch 7/100
94/94 [==============================] - 0s 654us/step - loss: 0.4763 - accuracy: 0.7716
Epoch 8/100
94/94 [==============================] - 0s 665us/step - loss: 0.4733 - accuracy: 0.7719
Epoch 9/100
94/94 [==============================] - 0s 676us/step - loss: 0.4720 - accuracy: 0.7676
Epoch 10/100
94/94 [==============================] - 0s 676us/step - loss: 0.4703 - accuracy: 0.7753
Epoch 11/100
94/94 [==============================] - 0s 686us/step - loss: 0.4685 - accuracy: 0.7726
Epoch 12/100
94/94 [==============================] - 0s 676us/step - loss: 0.4675 - accuracy: 0.7722
Epoch 13/100
94/94 [==============================] - 0s 665us/step - loss: 0.4661 - accuracy: 0.7722
Epoch 14/100
94/94 [==============================] - 0s 665us/step - loss: 0.4636 - accuracy: 0.7759
Epoch 15/100
94/94 [==============================] - 0s 665us/step - loss: 0.4637 - accuracy: 0.7719
Epoch 16/100
94/94 [==============================] - 0s 676us/step - loss: 0.4606 - accuracy: 0.7769
Epoch 17/100
94/94 [==============================] - 0s 665us/step - loss: 0.4602 - accuracy: 0.7783
Epoch 18/100
94/94 [==============================] - 0s 665us/step - loss: 0.4581 - accuracy: 0.7799
Epoch 19/100
94/94 [==============================] - 0s 665us/step - loss: 0.4579 - accuracy: 0.7803
Epoch 20/100
94/94 [==============================] - 0s 665us/step - loss: 0.4566 - accuracy: 0.7786
Epoch 21/100
94/94 [==============================] - 0s 665us/step - loss: 0.4563 - accuracy: 0.7796
Epoch 22/100
94/94 [==============================] - 0s 665us/step - loss: 0.4552 - accuracy: 0.7789
Epoch 23/100
94/94 [==============================] - 0s 686us/step - loss: 0.4524 - accuracy: 0.7809
Epoch 24/100
94/94 [==============================] - 0s 686us/step - loss: 0.4522 - accuracy: 0.7819
Epoch 25/100
94/94 [==============================] - 0s 676us/step - loss: 0.4521 - accuracy: 0.7776
Epoch 26/100
94/94 [==============================] - 0s 686us/step - loss: 0.4503 - accuracy: 0.7846
Epoch 27/100
94/94 [==============================] - 0s 676us/step - loss: 0.4486 - accuracy: 0.7880
Epoch 28/100
94/94 [==============================] - 0s 676us/step - loss: 0.4482 - accuracy: 0.7829
Epoch 29/100
94/94 [==============================] - 0s 676us/step - loss: 0.4478 - accuracy: 0.7809
Epoch 30/100
94/94 [==============================] - 0s 665us/step - loss: 0.4463 - accuracy: 0.7843
Epoch 31/100
94/94 [==============================] - 0s 665us/step - loss: 0.4446 - accuracy: 0.7856
Epoch 32/100
94/94 [==============================] - 0s 686us/step - loss: 0.4450 - accuracy: 0.7846
Epoch 33/100
94/94 [==============================] - 0s 693us/step - loss: 0.4430 - accuracy: 0.7853
Epoch 34/100
94/94 [==============================] - 0s 686us/step - loss: 0.4435 - accuracy: 0.7880
Epoch 35/100
94/94 [==============================] - 0s 672us/step - loss: 0.4407 - accuracy: 0.7849
Epoch 36/100
94/94 [==============================] - 0s 751us/step - loss: 0.4386 - accuracy: 0.7873
Epoch 37/100
94/94 [==============================] - 0s 708us/step - loss: 0.4397 - accuracy: 0.7893
Epoch 38/100
94/94 [==============================] - 0s 708us/step - loss: 0.4380 - accuracy: 0.7893
Epoch 39/100
94/94 [==============================] - 0s 718us/step - loss: 0.4371 - accuracy: 0.7933
Epoch 40/100
94/94 [==============================] - 0s 682us/step - loss: 0.4369 - accuracy: 0.7910
Epoch 41/100
94/94 [==============================] - 0s 676us/step - loss: 0.4346 - accuracy: 0.7946
Epoch 42/100
94/94 [==============================] - 0s 676us/step - loss: 0.4337 - accuracy: 0.7953
Epoch 43/100
94/94 [==============================] - 0s 676us/step - loss: 0.4330 - accuracy: 0.7943
Epoch 44/100
94/94 [==============================] - 0s 676us/step - loss: 0.4310 - accuracy: 0.7953
Epoch 45/100
94/94 [==============================] - 0s 686us/step - loss: 0.4316 - accuracy: 0.7926
Epoch 46/100
94/94 [==============================] - 0s 676us/step - loss: 0.4303 - accuracy: 0.7943
Epoch 47/100
94/94 [==============================] - 0s 697us/step - loss: 0.4300 - accuracy: 0.7923
Epoch 48/100
94/94 [==============================] - 0s 847us/step - loss: 0.4288 - accuracy: 0.7946
Epoch 49/100
94/94 [==============================] - 0s 718us/step - loss: 0.4288 - accuracy: 0.7977
Epoch 50/100
94/94 [==============================] - 0s 740us/step - loss: 0.4272 - accuracy: 0.7953
Epoch 51/100
94/94 [==============================] - 0s 708us/step - loss: 0.4268 - accuracy: 0.7950
Epoch 52/100
94/94 [==============================] - 0s 708us/step - loss: 0.4241 - accuracy: 0.8003
Epoch 53/100
94/94 [==============================] - 0s 708us/step - loss: 0.4252 - accuracy: 0.7943
Epoch 54/100
94/94 [==============================] - 0s 718us/step - loss: 0.4239 - accuracy: 0.7946
Epoch 55/100
94/94 [==============================] - 0s 725us/step - loss: 0.4259 - accuracy: 0.7960
Epoch 56/100
94/94 [==============================] - 0s 719us/step - loss: 0.4222 - accuracy: 0.8000
Epoch 57/100
94/94 [==============================] - 0s 719us/step - loss: 0.4211 - accuracy: 0.7980
Epoch 58/100
94/94 [==============================] - 0s 676us/step - loss: 0.4215 - accuracy: 0.7973
Epoch 59/100
94/94 [==============================] - 0s 665us/step - loss: 0.4221 - accuracy: 0.8003
Epoch 60/100
94/94 [==============================] - 0s 665us/step - loss: 0.4193 - accuracy: 0.8064
Epoch 61/100
94/94 [==============================] - 0s 665us/step - loss: 0.4188 - accuracy: 0.8057
Epoch 62/100
94/94 [==============================] - 0s 665us/step - loss: 0.4186 - accuracy: 0.8000
Epoch 63/100
94/94 [==============================] - 0s 650us/step - loss: 0.4169 - accuracy: 0.8023
Epoch 64/100
94/94 [==============================] - 0s 654us/step - loss: 0.4167 - accuracy: 0.7990
Epoch 65/100
94/94 [==============================] - 0s 665us/step - loss: 0.4157 - accuracy: 0.8023
Epoch 66/100
94/94 [==============================] - 0s 665us/step - loss: 0.4160 - accuracy: 0.8040
Epoch 67/100
94/94 [==============================] - 0s 676us/step - loss: 0.4149 - accuracy: 0.8030
Epoch 68/100
94/94 [==============================] - 0s 686us/step - loss: 0.4145 - accuracy: 0.8017
Epoch 69/100
94/94 [==============================] - 0s 676us/step - loss: 0.4150 - accuracy: 0.8007
Epoch 70/100
94/94 [==============================] - 0s 665us/step - loss: 0.4134 - accuracy: 0.8067
Epoch 71/100
94/94 [==============================] - 0s 665us/step - loss: 0.4126 - accuracy: 0.8064
Epoch 72/100
94/94 [==============================] - 0s 665us/step - loss: 0.4123 - accuracy: 0.8064
Epoch 73/100
94/94 [==============================] - 0s 676us/step - loss: 0.4108 - accuracy: 0.8060
Epoch 74/100
94/94 [==============================] - 0s 671us/step - loss: 0.4139 - accuracy: 0.8020
Epoch 75/100
94/94 [==============================] - 0s 676us/step - loss: 0.4092 - accuracy: 0.8060
Epoch 76/100
94/94 [==============================] - 0s 676us/step - loss: 0.4099 - accuracy: 0.8084
Epoch 77/100
94/94 [==============================] - 0s 665us/step - loss: 0.4132 - accuracy: 0.8050
Epoch 78/100
94/94 [==============================] - 0s 665us/step - loss: 0.4072 - accuracy: 0.8100
Epoch 79/100
94/94 [==============================] - 0s 665us/step - loss: 0.4082 - accuracy: 0.8040
Epoch 80/100
94/94 [==============================] - 0s 665us/step - loss: 0.4067 - accuracy: 0.8067
Epoch 81/100

94/94 [==============================] - 0s 665us/step - loss: 0.4088 - accuracy: 0.8087
Epoch 82/100
94/94 [==============================] - 0s 665us/step - loss: 0.4080 - accuracy: 0.8060
Epoch 83/100
94/94 [==============================] - 0s 676us/step - loss: 0.4057 - accuracy: 0.8130
Epoch 84/100
94/94 [==============================] - 0s 665us/step - loss: 0.4058 - accuracy: 0.8060
Epoch 85/100
94/94 [==============================] - 0s 665us/step - loss: 0.4050 - accuracy: 0.8097
Epoch 86/100
94/94 [==============================] - 0s 676us/step - loss: 0.4034 - accuracy: 0.8107
Epoch 87/100
94/94 [==============================] - 0s 665us/step - loss: 0.4043 - accuracy: 0.8097
Epoch 88/100
94/94 [==============================] - 0s 676us/step - loss: 0.4050 - accuracy: 0.8064
Epoch 89/100
94/94 [==============================] - 0s 665us/step - loss: 0.4036 - accuracy: 0.8134
Epoch 90/100
94/94 [==============================] - 0s 654us/step - loss: 0.4012 - accuracy: 0.8104
Epoch 91/100
94/94 [==============================] - 0s 665us/step - loss: 0.4024 - accuracy: 0.8114
Epoch 92/100
94/94 [==============================] - 0s 654us/step - loss: 0.4022 - accuracy: 0.8097
Epoch 93/100
94/94 [==============================] - 0s 665us/step - loss: 0.4004 - accuracy: 0.8084
Epoch 94/100
94/94 [==============================] - 0s 665us/step - loss: 0.4000 - accuracy: 0.8134
Epoch 95/100
94/94 [==============================] - 0s 654us/step - loss: 0.3985 - accuracy: 0.8164
Epoch 96/100
94/94 [==============================] - 0s 654us/step - loss: 0.3976 - accuracy: 0.8130
Epoch 97/100
94/94 [==============================] - 0s 654us/step - loss: 0.3991 - accuracy: 0.8130
Epoch 98/100
94/94 [==============================] - 0s 665us/step - loss: 0.3999 - accuracy: 0.8147
Epoch 99/100
94/94 [==============================] - 0s 654us/step - loss: 0.3973 - accuracy: 0.8140
Epoch 100/100
94/94 [==============================] - 0s 665us/step - loss: 0.3965 - accuracy: 0.8114
24/24 [==============================] - 0s 631us/step - loss: 0.5401 - accuracy: 0.7540
[0.5401415228843689, 0.7540106773376465]
24/24 [==============================] - 0s 581us/step
classification report:
               precision    recall  f1-score   support

           0       0.77      0.72      0.75       374
           1       0.74      0.78      0.76       374

    accuracy                           0.75       748
   macro avg       0.75      0.75      0.75       748
weighted avg       0.75      0.75      0.75       748

METHOD 2:OVER SAMPLING:

In [77]:
count_class_0,count_class_1

(5163, 1869)

In [79]:
df_class_1.sample(2000,replace=True).shape

(2000, 27)

In [84]:
df_class_1_over=df_class_1.sample(count_class_0,replace=True)
df_test_over=pd.concat([df_class_0,df_class_1_over],axis=0)
print('Random over-sampling:')
print(df_test_over.Churn.value_counts())

Random over-sampling:
0    5163
1    5163
Name: Churn, dtype: int64

In [83]:
df_test_over.shape

(10326, 27)

In [87]:
x=df_test_over.drop('Churn',axis=1)
y=df_test_over['Churn']

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=15,stratify=y)

In [91]:
y_train.value_counts()

1    4130
0    4130
Name: Churn, dtype: int64

y_pred=ANN(x_train,y_train,x_test,y_test,'binary_crossentropy')

In [93]:
y_pred=ANN(x_train,y_train,x_test,y_test,'binary_crossentropy')

Epoch 1/100
259/259 [==============================] - 1s 661us/step - loss: 0.5524 - accuracy: 0.7173
Epoch 2/100
259/259 [==============================] - 0s 665us/step - loss: 0.4909 - accuracy: 0.7614
Epoch 3/100
259/259 [==============================] - 0s 661us/step - loss: 0.4809 - accuracy: 0.7667
Epoch 4/100
259/259 [==============================] - 0s 661us/step - loss: 0.4751 - accuracy: 0.7713
Epoch 5/100
259/259 [==============================] - 0s 665us/step - loss: 0.4709 - accuracy: 0.7749
Epoch 6/100
259/259 [==============================] - 0s 673us/step - loss: 0.4682 - accuracy: 0.7738
Epoch 7/100
259/259 [==============================] - 0s 669us/step - loss: 0.4641 - accuracy: 0.7799
Epoch 8/100
259/259 [==============================] - 0s 673us/step - loss: 0.4627 - accuracy: 0.7781
Epoch 9/100
259/259 [==============================] - 0s 669us/step - loss: 0.4597 - accuracy: 0.7782
Epoch 10/100
259/259 [==============================] - 0s 665us/step - loss: 0.4564 - accuracy: 0.7806
Epoch 11/100
259/259 [==============================] - 0s 663us/step - loss: 0.4541 - accuracy: 0.7858
Epoch 12/100
259/259 [==============================] - 0s 665us/step - loss: 0.4519 - accuracy: 0.7855
Epoch 13/100
259/259 [==============================] - 0s 665us/step - loss: 0.4489 - accuracy: 0.7860
Epoch 14/100
259/259 [==============================] - 0s 669us/step - loss: 0.4470 - accuracy: 0.7898
Epoch 15/100
259/259 [==============================] - 0s 676us/step - loss: 0.4454 - accuracy: 0.7929
Epoch 16/100
259/259 [==============================] - 0s 671us/step - loss: 0.4441 - accuracy: 0.7915
Epoch 17/100
259/259 [==============================] - 0s 731us/step - loss: 0.4410 - accuracy: 0.7933
Epoch 18/100
259/259 [==============================] - 0s 676us/step - loss: 0.4399 - accuracy: 0.7921
Epoch 19/100
259/259 [==============================] - 0s 687us/step - loss: 0.4392 - accuracy: 0.7932
Epoch 20/100
259/259 [==============================] - 0s 665us/step - loss: 0.4355 - accuracy: 0.7950
Epoch 21/100
259/259 [==============================] - 0s 683us/step - loss: 0.4340 - accuracy: 0.7966
Epoch 22/100
259/259 [==============================] - 0s 675us/step - loss: 0.4330 - accuracy: 0.7938
Epoch 23/100
259/259 [==============================] - 0s 665us/step - loss: 0.4299 - accuracy: 0.7978
Epoch 24/100
259/259 [==============================] - 0s 673us/step - loss: 0.4303 - accuracy: 0.7993
Epoch 25/100
259/259 [==============================] - 0s 673us/step - loss: 0.4284 - accuracy: 0.8033
Epoch 26/100
259/259 [==============================] - 0s 661us/step - loss: 0.4266 - accuracy: 0.8022
Epoch 27/100
259/259 [==============================] - 0s 665us/step - loss: 0.4241 - accuracy: 0.8041
Epoch 28/100
259/259 [==============================] - 0s 661us/step - loss: 0.4241 - accuracy: 0.8047
Epoch 29/100
259/259 [==============================] - 0s 661us/step - loss: 0.4227 - accuracy: 0.8068
Epoch 30/100
259/259 [==============================] - 0s 665us/step - loss: 0.4211 - accuracy: 0.8061
Epoch 31/100
259/259 [==============================] - 0s 665us/step - loss: 0.4194 - accuracy: 0.8080
Epoch 32/100
259/259 [==============================] - 0s 669us/step - loss: 0.4188 - accuracy: 0.8063
Epoch 33/100
259/259 [==============================] - 0s 665us/step - loss: 0.4164 - accuracy: 0.8098
Epoch 34/100
259/259 [==============================] - 0s 663us/step - loss: 0.4170 - accuracy: 0.8087
Epoch 35/100
259/259 [==============================] - 0s 665us/step - loss: 0.4148 - accuracy: 0.8108
Epoch 36/100
259/259 [==============================] - 0s 676us/step - loss: 0.4140 - accuracy: 0.8119
Epoch 37/100
259/259 [==============================] - 0s 714us/step - loss: 0.4129 - accuracy: 0.8113
Epoch 38/100
259/259 [==============================] - 0s 692us/step - loss: 0.4113 - accuracy: 0.8132
Epoch 39/100
259/259 [==============================] - 0s 684us/step - loss: 0.4102 - accuracy: 0.8171
Epoch 40/100
259/259 [==============================] - 0s 688us/step - loss: 0.4082 - accuracy: 0.8143
Epoch 41/100
259/259 [==============================] - 0s 719us/step - loss: 0.4083 - accuracy: 0.8157
Epoch 42/100
259/259 [==============================] - 0s 725us/step - loss: 0.4065 - accuracy: 0.8144
Epoch 43/100
259/259 [==============================] - 0s 715us/step - loss: 0.4064 - accuracy: 0.8167
Epoch 44/100
259/259 [==============================] - 0s 688us/step - loss: 0.4049 - accuracy: 0.8166
Epoch 45/100
259/259 [==============================] - 0s 702us/step - loss: 0.4040 - accuracy: 0.8177
Epoch 46/100
259/259 [==============================] - 0s 663us/step - loss: 0.4025 - accuracy: 0.8194
Epoch 47/100
259/259 [==============================] - 0s 665us/step - loss: 0.4019 - accuracy: 0.8190
Epoch 48/100
259/259 [==============================] - 0s 675us/step - loss: 0.4019 - accuracy: 0.8201
Epoch 49/100
259/259 [==============================] - 0s 669us/step - loss: 0.4002 - accuracy: 0.8218
Epoch 50/100
259/259 [==============================] - 0s 668us/step - loss: 0.3985 - accuracy: 0.8229
Epoch 51/100
259/259 [==============================] - 0s 669us/step - loss: 0.3992 - accuracy: 0.8186
Epoch 52/100
259/259 [==============================] - 0s 661us/step - loss: 0.3967 - accuracy: 0.8223
Epoch 53/100
259/259 [==============================] - 0s 665us/step - loss: 0.3965 - accuracy: 0.8212
Epoch 54/100
259/259 [==============================] - 0s 661us/step - loss: 0.3956 - accuracy: 0.8242
Epoch 55/100
259/259 [==============================] - 0s 669us/step - loss: 0.3944 - accuracy: 0.8240
Epoch 56/100
259/259 [==============================] - 0s 673us/step - loss: 0.3942 - accuracy: 0.8238
Epoch 57/100
259/259 [==============================] - 0s 676us/step - loss: 0.3927 - accuracy: 0.8248
Epoch 58/100
259/259 [==============================] - 0s 676us/step - loss: 0.3916 - accuracy: 0.8247
Epoch 59/100
259/259 [==============================] - 0s 684us/step - loss: 0.3908 - accuracy: 0.8229
Epoch 60/100
259/259 [==============================] - 0s 667us/step - loss: 0.3895 - accuracy: 0.8275
Epoch 61/100
259/259 [==============================] - 0s 673us/step - loss: 0.3891 - accuracy: 0.8265
Epoch 62/100
259/259 [==============================] - 0s 679us/step - loss: 0.3870 - accuracy: 0.8266
Epoch 63/100
259/259 [==============================] - 0s 669us/step - loss: 0.3873 - accuracy: 0.8259
Epoch 64/100
259/259 [==============================] - 0s 667us/step - loss: 0.3850 - accuracy: 0.8237
Epoch 65/100
259/259 [==============================] - 0s 673us/step - loss: 0.3847 - accuracy: 0.8289
Epoch 66/100
259/259 [==============================] - 0s 665us/step - loss: 0.3844 - accuracy: 0.8286
Epoch 67/100
259/259 [==============================] - 0s 684us/step - loss: 0.3835 - accuracy: 0.8266
Epoch 68/100
259/259 [==============================] - 0s 669us/step - loss: 0.3822 - accuracy: 0.8281
Epoch 69/100
259/259 [==============================] - 0s 665us/step - loss: 0.3804 - accuracy: 0.8310
Epoch 70/100
259/259 [==============================] - 0s 665us/step - loss: 0.3805 - accuracy: 0.8285
Epoch 71/100
259/259 [==============================] - 0s 665us/step - loss: 0.3797 - accuracy: 0.8310
Epoch 72/100
259/259 [==============================] - 0s 669us/step - loss: 0.3793 - accuracy: 0.8281
Epoch 73/100
259/259 [==============================] - 0s 663us/step - loss: 0.3769 - accuracy: 0.8323
Epoch 74/100
259/259 [==============================] - 0s 665us/step - loss: 0.3756 - accuracy: 0.8322
Epoch 75/100
259/259 [==============================] - 0s 661us/step - loss: 0.3758 - accuracy: 0.8335
Epoch 76/100
259/259 [==============================] - 0s 665us/step - loss: 0.3749 - accuracy: 0.8337
Epoch 77/100
259/259 [==============================] - 0s 665us/step - loss: 0.3731 - accuracy: 0.8362
Epoch 78/100
259/259 [==============================] - 0s 665us/step - loss: 0.3722 - accuracy: 0.8327
Epoch 79/100

259/259 [==============================] - 0s 661us/step - loss: 0.3736 - accuracy: 0.8332
Epoch 80/100
259/259 [==============================] - 0s 663us/step - loss: 0.3709 - accuracy: 0.8366
Epoch 81/100
259/259 [==============================] - 0s 663us/step - loss: 0.3700 - accuracy: 0.8339
Epoch 82/100
259/259 [==============================] - 0s 661us/step - loss: 0.3693 - accuracy: 0.8372
Epoch 83/100
259/259 [==============================] - 0s 661us/step - loss: 0.3695 - accuracy: 0.8368
Epoch 84/100
259/259 [==============================] - 0s 665us/step - loss: 0.3685 - accuracy: 0.8369
Epoch 85/100
259/259 [==============================] - 0s 661us/step - loss: 0.3667 - accuracy: 0.8380
Epoch 86/100
259/259 [==============================] - 0s 667us/step - loss: 0.3667 - accuracy: 0.8381
Epoch 87/100
259/259 [==============================] - 0s 669us/step - loss: 0.3675 - accuracy: 0.8383
Epoch 88/100
259/259 [==============================] - 0s 711us/step - loss: 0.3657 - accuracy: 0.8373
Epoch 89/100
259/259 [==============================] - 0s 665us/step - loss: 0.3645 - accuracy: 0.8377
Epoch 90/100
259/259 [==============================] - 0s 657us/step - loss: 0.3634 - accuracy: 0.8392
Epoch 91/100
259/259 [==============================] - 0s 661us/step - loss: 0.3637 - accuracy: 0.8396
Epoch 92/100
259/259 [==============================] - 0s 669us/step - loss: 0.3628 - accuracy: 0.8380
Epoch 93/100
259/259 [==============================] - 0s 669us/step - loss: 0.3623 - accuracy: 0.8408
Epoch 94/100
259/259 [==============================] - 0s 657us/step - loss: 0.3623 - accuracy: 0.8364
Epoch 95/100
259/259 [==============================] - 0s 661us/step - loss: 0.3605 - accuracy: 0.8409
Epoch 96/100
259/259 [==============================] - 0s 669us/step - loss: 0.3602 - accuracy: 0.8430
Epoch 97/100
259/259 [==============================] - 0s 665us/step - loss: 0.3603 - accuracy: 0.8430
Epoch 98/100
259/259 [==============================] - 0s 661us/step - loss: 0.3573 - accuracy: 0.8415
Epoch 99/100
259/259 [==============================] - 0s 665us/step - loss: 0.3598 - accuracy: 0.8410
Epoch 100/100
259/259 [==============================] - 0s 661us/step - loss: 0.3577 - accuracy: 0.8408
65/65 [==============================] - 0s 561us/step - loss: 0.4897 - accuracy: 0.7730
[0.489724725484848, 0.7729912996292114]
65/65 [==============================] - 0s 491us/step
classification report:
               precision    recall  f1-score   support

           0       0.81      0.71      0.76      1033
           1       0.74      0.83      0.79      1033

    accuracy                           0.77      2066
   macro avg       0.78      0.77      0.77      2066
weighted avg       0.78      0.77      0.77      2066

METHOD 3: SMOTE

In [94]:
x=df2.drop('Churn',axis=1)
y=df2['Churn']

In [96]:
pip install imbalanced_learn

Defaulting to user installation because normal site-packages is not writeable
Collecting imbalanced_learn
  Downloading imbalanced_learn-0.9.1-py3-none-any.whl (199 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced_learn) (2.2.0)
Requirement already satisfied: joblib>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced_learn) (1.1.0)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from imbalanced_learn) (1.21.5)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced_learn) (1.7.3)
Collecting scikit-learn>=1.1.0
  Downloading scikit_learn-1.1.2-cp39-cp39-win_amd64.whl (7.4 MB)
Installing collected packages: scikit-learn, imbalanced-learn
Successfully installed imbalanced-learn-0.9.1 scikit-learn-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [99]:
from imblearn.over_sampling import SMOTE

In [101]:
smote=SMOTE(sampling_strategy='minority')
x_sm,y_sm=smote.fit_resample(x,y)

In [102]:
y_sm.value_counts()

0    5163
1    5163
Name: Churn, dtype: int64

In [103]:
x_sm.value_counts()

gender  SeniorCitizen  Partner  Dependents  tenure    PhoneService  MultipleLines  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  PaperlessBilling  MonthlyCharges  TotalCharges  InternetService_0  InternetService_DSL  InternetService_Fiber optic  Contract_Month-to-month  Contract_One year  Contract_Two year  PaymentMethod_Bank transfer (automatic)  PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  PaymentMethod_Mailed check
1       1              0        0           0.000000  1             0              0               0             0                 0            0            0                1                 0.510945        0.005862      0                  0                    1                            1                        0                  0                  0                                        0                                      1                               0                             5
0       0              0        0           0.000000  1             0              0               0             0                 0            0            0                0                 0.269154        0.003058      0                  1                    0                            1                        0                  0                  0                                        0                                      1                               0                             4
                                                                                                                                                                                                0.018905        0.000156      1                  0                    0                            1                        0                  0                  0                                        0                                      0                               1                             4
1       0              0        0           0.000000  1             0              0               0             0                 0            0            0                0                 0.026368        0.000242      1                  0                    0                            1                        0                  0                  0                                        0                                      0                               1                             4
0       0              0        0           0.000000  1             0              0               0             0                 0            0            0                0                 0.019403        0.000162      1                  0                    0                            1                        0                  0                  0                                        0                                      0                               1                             4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
                       1        0           0.971831  1             1              0               1             1                 1            1            0                0                 0.575622        0.605291      0                  1                    0                            0                        0                  1                  0                                        1                                      0                               0                             1
                                                                                   1               0             0                 1            1            1                1                 0.584080        0.608239      0                  1                    0                            0                        0                  1                  0                                        1                                      0                               0                             1
                                                                                                                 1                 1            0            1                0                 0.587562        0.632287      0                  1                    0                            0                        0                  1                  0                                        1                                      0                               0                             1
                                                                                                                                                                              1                 0.562687        0.611239      0                  1                    0                            0                        0                  1                  0                                        1                                      0                               0                             1
1       1              1        1           1.000000  1             1              1               1             1                 1            1            1                1                 0.715423        0.772865      0                  1                    0                            0                        0                  1                  1                                        0                                      0                               0                             1
Length: 10270, dtype: int64

In [105]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_sm,y_sm,test_size=0.2,random_state=15,stratify=y_sm)

In [106]:
y_train.value_counts()

1    4130
0    4130
Name: Churn, dtype: int64

In [107]:
y_test.value_counts()

1    1033
0    1033
Name: Churn, dtype: int64

In [108]:
y_pred=ANN(x_train,y_train,x_test,y_test,'binary_crossentropy')

Epoch 1/100
259/259 [==============================] - 1s 653us/step - loss: 0.5259 - accuracy: 0.7472
Epoch 2/100
259/259 [==============================] - 0s 657us/step - loss: 0.4663 - accuracy: 0.7793
Epoch 3/100
259/259 [==============================] - 0s 657us/step - loss: 0.4587 - accuracy: 0.7832
Epoch 4/100
259/259 [==============================] - 0s 665us/step - loss: 0.4536 - accuracy: 0.7879
Epoch 5/100
259/259 [==============================] - 0s 665us/step - loss: 0.4488 - accuracy: 0.7912
Epoch 6/100
259/259 [==============================] - 0s 665us/step - loss: 0.4458 - accuracy: 0.7919
Epoch 7/100
259/259 [==============================] - 0s 665us/step - loss: 0.4415 - accuracy: 0.7953
Epoch 8/100
259/259 [==============================] - 0s 711us/step - loss: 0.4373 - accuracy: 0.7947
Epoch 9/100
259/259 [==============================] - 0s 702us/step - loss: 0.4332 - accuracy: 0.7965
Epoch 10/100
259/259 [==============================] - 0s 675us/step - loss: 0.4303 - accuracy: 0.8000
Epoch 11/100
259/259 [==============================] - 0s 669us/step - loss: 0.4271 - accuracy: 0.8045
Epoch 12/100
259/259 [==============================] - 0s 680us/step - loss: 0.4242 - accuracy: 0.8024
Epoch 13/100
259/259 [==============================] - 0s 707us/step - loss: 0.4204 - accuracy: 0.8073
Epoch 14/100
259/259 [==============================] - 0s 694us/step - loss: 0.4183 - accuracy: 0.8070
Epoch 15/100
259/259 [==============================] - 0s 708us/step - loss: 0.4153 - accuracy: 0.8098
Epoch 16/100
259/259 [==============================] - 0s 688us/step - loss: 0.4118 - accuracy: 0.8102
Epoch 17/100
259/259 [==============================] - 0s 663us/step - loss: 0.4089 - accuracy: 0.8110
Epoch 18/100
259/259 [==============================] - 0s 676us/step - loss: 0.4054 - accuracy: 0.8151
Epoch 19/100
259/259 [==============================] - 0s 710us/step - loss: 0.4030 - accuracy: 0.8146
Epoch 20/100
259/259 [==============================] - 0s 676us/step - loss: 0.3998 - accuracy: 0.8197
Epoch 21/100
259/259 [==============================] - 0s 669us/step - loss: 0.3969 - accuracy: 0.8214
Epoch 22/100
259/259 [==============================] - 0s 673us/step - loss: 0.3960 - accuracy: 0.8213
Epoch 23/100
259/259 [==============================] - 0s 673us/step - loss: 0.3956 - accuracy: 0.8195
Epoch 24/100
259/259 [==============================] - 0s 675us/step - loss: 0.3911 - accuracy: 0.8234
Epoch 25/100
259/259 [==============================] - 0s 673us/step - loss: 0.3888 - accuracy: 0.8245
Epoch 26/100
259/259 [==============================] - 0s 680us/step - loss: 0.3870 - accuracy: 0.8251
Epoch 27/100
259/259 [==============================] - 0s 673us/step - loss: 0.3861 - accuracy: 0.8278
Epoch 28/100
259/259 [==============================] - 0s 679us/step - loss: 0.3850 - accuracy: 0.8270
Epoch 29/100
259/259 [==============================] - 0s 680us/step - loss: 0.3804 - accuracy: 0.8286
Epoch 30/100
259/259 [==============================] - 0s 669us/step - loss: 0.3796 - accuracy: 0.8278
Epoch 31/100
259/259 [==============================] - 0s 673us/step - loss: 0.3795 - accuracy: 0.8275
Epoch 32/100
259/259 [==============================] - 0s 680us/step - loss: 0.3780 - accuracy: 0.8316
Epoch 33/100
259/259 [==============================] - 0s 680us/step - loss: 0.3770 - accuracy: 0.8315
Epoch 34/100
259/259 [==============================] - 0s 676us/step - loss: 0.3737 - accuracy: 0.8303
Epoch 35/100
259/259 [==============================] - 0s 676us/step - loss: 0.3738 - accuracy: 0.8311
Epoch 36/100
259/259 [==============================] - 0s 657us/step - loss: 0.3727 - accuracy: 0.8322
Epoch 37/100
259/259 [==============================] - 0s 657us/step - loss: 0.3719 - accuracy: 0.8335
Epoch 38/100
259/259 [==============================] - 0s 653us/step - loss: 0.3676 - accuracy: 0.8381
Epoch 39/100
259/259 [==============================] - 0s 657us/step - loss: 0.3698 - accuracy: 0.8346
Epoch 40/100
259/259 [==============================] - 0s 661us/step - loss: 0.3661 - accuracy: 0.8369
Epoch 41/100
259/259 [==============================] - 0s 669us/step - loss: 0.3660 - accuracy: 0.8361
Epoch 42/100
259/259 [==============================] - 0s 663us/step - loss: 0.3638 - accuracy: 0.8383
Epoch 43/100
259/259 [==============================] - 0s 665us/step - loss: 0.3631 - accuracy: 0.8386
Epoch 44/100
259/259 [==============================] - 0s 661us/step - loss: 0.3613 - accuracy: 0.8379
Epoch 45/100
259/259 [==============================] - 0s 657us/step - loss: 0.3607 - accuracy: 0.8368
Epoch 46/100
259/259 [==============================] - 0s 704us/step - loss: 0.3601 - accuracy: 0.8390
Epoch 47/100
259/259 [==============================] - 0s 661us/step - loss: 0.3602 - accuracy: 0.8409
Epoch 48/100
259/259 [==============================] - 0s 665us/step - loss: 0.3575 - accuracy: 0.8410
Epoch 49/100
259/259 [==============================] - 0s 669us/step - loss: 0.3564 - accuracy: 0.8426
Epoch 50/100
259/259 [==============================] - 0s 669us/step - loss: 0.3567 - accuracy: 0.8384
Epoch 51/100
259/259 [==============================] - 0s 669us/step - loss: 0.3553 - accuracy: 0.8413
Epoch 52/100
259/259 [==============================] - 0s 676us/step - loss: 0.3531 - accuracy: 0.8433
Epoch 53/100
259/259 [==============================] - 0s 661us/step - loss: 0.3535 - accuracy: 0.8429
Epoch 54/100
259/259 [==============================] - 0s 657us/step - loss: 0.3509 - accuracy: 0.8454
Epoch 55/100
259/259 [==============================] - 0s 661us/step - loss: 0.3525 - accuracy: 0.8441
Epoch 56/100
259/259 [==============================] - 0s 661us/step - loss: 0.3491 - accuracy: 0.8462
Epoch 57/100
259/259 [==============================] - 0s 663us/step - loss: 0.3496 - accuracy: 0.8453
Epoch 58/100
259/259 [==============================] - 0s 661us/step - loss: 0.3501 - accuracy: 0.8470
Epoch 59/100
259/259 [==============================] - 0s 669us/step - loss: 0.3482 - accuracy: 0.8461
Epoch 60/100
259/259 [==============================] - 0s 657us/step - loss: 0.3483 - accuracy: 0.8473
Epoch 61/100
259/259 [==============================] - 0s 661us/step - loss: 0.3491 - accuracy: 0.8435
Epoch 62/100
259/259 [==============================] - 0s 657us/step - loss: 0.3477 - accuracy: 0.8475
Epoch 63/100
259/259 [==============================] - 0s 663us/step - loss: 0.3454 - accuracy: 0.8489
Epoch 64/100
259/259 [==============================] - 0s 665us/step - loss: 0.3443 - accuracy: 0.8488
Epoch 65/100
259/259 [==============================] - 0s 657us/step - loss: 0.3452 - accuracy: 0.8471
Epoch 66/100
259/259 [==============================] - 0s 657us/step - loss: 0.3436 - accuracy: 0.8484
Epoch 67/100
259/259 [==============================] - 0s 657us/step - loss: 0.3422 - accuracy: 0.8492
Epoch 68/100
259/259 [==============================] - 0s 657us/step - loss: 0.3419 - accuracy: 0.8469
Epoch 69/100
259/259 [==============================] - 0s 676us/step - loss: 0.3420 - accuracy: 0.8492
Epoch 70/100
259/259 [==============================] - 0s 665us/step - loss: 0.3398 - accuracy: 0.8502
Epoch 71/100
259/259 [==============================] - 0s 661us/step - loss: 0.3428 - accuracy: 0.8484
Epoch 72/100
259/259 [==============================] - 0s 669us/step - loss: 0.3400 - accuracy: 0.8465
Epoch 73/100
259/259 [==============================] - 0s 673us/step - loss: 0.3401 - accuracy: 0.8489
Epoch 74/100
259/259 [==============================] - 0s 704us/step - loss: 0.3375 - accuracy: 0.8523
Epoch 75/100
259/259 [==============================] - 0s 657us/step - loss: 0.3385 - accuracy: 0.8511
Epoch 76/100
259/259 [==============================] - 0s 661us/step - loss: 0.3380 - accuracy: 0.8528
Epoch 77/100
259/259 [==============================] - 0s 667us/step - loss: 0.3375 - accuracy: 0.8498
Epoch 78/100
259/259 [==============================] - 0s 661us/step - loss: 0.3388 - accuracy: 0.8489
Epoch 79/100

259/259 [==============================] - 0s 665us/step - loss: 0.3366 - accuracy: 0.8518
Epoch 80/100
259/259 [==============================] - 0s 665us/step - loss: 0.3349 - accuracy: 0.8508
Epoch 81/100
259/259 [==============================] - 0s 657us/step - loss: 0.3353 - accuracy: 0.8507
Epoch 82/100
259/259 [==============================] - 0s 676us/step - loss: 0.3347 - accuracy: 0.8500
Epoch 83/100
259/259 [==============================] - 0s 663us/step - loss: 0.3328 - accuracy: 0.8527
Epoch 84/100
259/259 [==============================] - 0s 661us/step - loss: 0.3351 - accuracy: 0.8558
Epoch 85/100
259/259 [==============================] - 0s 665us/step - loss: 0.3366 - accuracy: 0.8515
Epoch 86/100
259/259 [==============================] - 0s 659us/step - loss: 0.3351 - accuracy: 0.8528
Epoch 87/100
259/259 [==============================] - 0s 657us/step - loss: 0.3349 - accuracy: 0.8531
Epoch 88/100
259/259 [==============================] - 0s 657us/step - loss: 0.3323 - accuracy: 0.8518
Epoch 89/100
259/259 [==============================] - 0s 661us/step - loss: 0.3337 - accuracy: 0.8556
Epoch 90/100
259/259 [==============================] - 0s 657us/step - loss: 0.3329 - accuracy: 0.8539
Epoch 91/100
259/259 [==============================] - 0s 665us/step - loss: 0.3319 - accuracy: 0.8563
Epoch 92/100
259/259 [==============================] - 0s 661us/step - loss: 0.3327 - accuracy: 0.8563
Epoch 93/100
259/259 [==============================] - 0s 665us/step - loss: 0.3283 - accuracy: 0.8552
Epoch 94/100
259/259 [==============================] - 0s 657us/step - loss: 0.3284 - accuracy: 0.8565
Epoch 95/100
259/259 [==============================] - 0s 665us/step - loss: 0.3296 - accuracy: 0.8573
Epoch 96/100
259/259 [==============================] - 0s 665us/step - loss: 0.3292 - accuracy: 0.8547
Epoch 97/100
259/259 [==============================] - 0s 656us/step - loss: 0.3294 - accuracy: 0.8546
Epoch 98/100
259/259 [==============================] - 0s 657us/step - loss: 0.3272 - accuracy: 0.8575
Epoch 99/100
259/259 [==============================] - 0s 704us/step - loss: 0.3282 - accuracy: 0.8564
Epoch 100/100
259/259 [==============================] - 0s 702us/step - loss: 0.3277 - accuracy: 0.8554
65/65 [==============================] - 0s 577us/step - loss: 0.4493 - accuracy: 0.8020
[0.44925326108932495, 0.8020328879356384]
65/65 [==============================] - 0s 499us/step
classification report:
               precision    recall  f1-score   support

           0       0.82      0.78      0.80      1033
           1       0.79      0.82      0.81      1033

    accuracy                           0.80      2066
   macro avg       0.80      0.80      0.80      2066
weighted avg       0.80      0.80      0.80      2066